title: My Project Documentation
description: This is my project's documentation site.
theme: minima

# 启用 Jekyll Mermaid 插件
plugins:
  - jekyll-mermaid

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable : true